package com.rafaelmfer.consultinggithub.model.pullrequests

import com.google.gson.annotations.SerializedName

data class GitPullRequestResponse(
    @SerializedName("url") val url: String,
    @SerializedName("id") val id: Int,
    @SerializedName("node_id") val nodeId: String,
    @SerializedName("html_url") val htmlUrl: String,
    @SerializedName("diff_url") val diffUrl: String,
    @SerializedName("patch_url") val patchUrl: String,
    @SerializedName("issue_url") val issueUrl: String,
    @SerializedName("number") val number: Int,
    @SerializedName("state") val state: String,
    @SerializedName("locked") val locked: Boolean,
    @SerializedName("title") val title: String,
    @SerializedName("user") val user: User,
    @SerializedName("body") val body: String,
    @SerializedName("created_at") val createdAt: String,
    @SerializedName("updated_at") val updatedAt: String,
    @SerializedName("merge_commit_sha") val mergeCommitSha: String,
    @SerializedName("assignees") val assignees: List<Any>,
    @SerializedName("requested_reviewers") val requestedReviewers: List<Any>,
    @SerializedName("requested_teams") val requestedTeams: List<Any>,
    @SerializedName("labels") val labels: List<Any>,
    @SerializedName("draft") val draft: Boolean,
    @SerializedName("commits_url") val commitsUrl: String,
    @SerializedName("review_comments_url") val reviewCommentsUrl: String,
    @SerializedName("review_comment_url") val reviewCommentUrl: String,
    @SerializedName("comments_url") val commentsUrl: String,
    @SerializedName("statuses_url") val statusesUrl: String,
    @SerializedName("head") val head: Head,
    @SerializedName("base") val base: Base,
    @SerializedName("_links") val links: Links,
    @SerializedName("author_association") val authorAssociation: String,
    @SerializedName("closed_at") val closedAt: Any,
    @SerializedName("merged_at") val mergedAt: Any,
    @SerializedName("assignee") val assignee: Any,
    @SerializedName("milestone") val milestone: Any
)