name: Feature/Fix branches CI

on:
  push:
    branches:
      - 'feature/*'
      - 'feature/**'
      - 'refact/*'
      - 'refact/**'
      - 'fix/*'
      - 'fix/**'
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  klint:
    name: Run ktlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ktlint
        run: bash ./gradlew ktlint --stacktrace